# Generated by Django 3.1.4 on 2020-12-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201214_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, upload_to='Images/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.note', verbose_name='Номер статьи'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(max_length=45, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='note',
            name='article',
            field=models.TextField(max_length=400, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Название статьи'),
        ),
    ]
