# Generated by Django 3.1.4 on 2020-12-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201218_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/Images/%Y-%m-%d'),
        ),
    ]
