# Generated by Django 3.1.4 on 2020-12-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201218_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='article',
            field=models.TextField(max_length=1000, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/Images/%Y-%m-%d', verbose_name='Фото статьи'),
        ),
    ]
