# Generated by Django 3.1.4 on 2020-12-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201226_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='article',
            field=models.TextField(max_length=3000, verbose_name='Текст статьи'),
        ),
    ]
