# Generated by Django 3.1.4 on 2021-01-02 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20210102_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(10), to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
    ]
